version: '3.8'

services:
  django:
    build:
      context: .
    container_name: django_app
    volumes:
      - ./template_django:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/product_images
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoHUD.settings
    command: ["gunicorn", "DjangoHUD.wsgi:application", "--bind", "0.0.0.0:8000"]
    restart: always

volumes:
  static_volume:
  media_volume:
