version: '3.8'

services:
  django:
    build:
      context: .
    container_name: django_app
    volumes:
      - ./template_django:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/product_images
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoHUD.settings
    command: ["gunicorn", "DjangoHUD.wsgi:application", "--bind", "0.0.0.0:8000"]
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/product_images
    depends_on:
      - django
    restart: always

volumes:
  static_volume:
  media_volume:
