# Generated by Django 5.0.1 on 2024-02-28 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('serial_number', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('ΔΡΟΜΟΛΟΓΗΤΗΣ', 'ΔΡΟΜΟΛΟΓΗΤΗΣ'), ('CONVERTER', 'CONVERTER'), ('SWITCH', 'SWITCH'), ('MODULE', 'MODULE'), ('ΜΕΤΑΤΡΟΠΕΑΣ', 'ΜΕΤΑΤΡΟΠΕΑΣ'), ('LAN EXTENDER', 'LAN EXTENDER'), ('ΚΑΛΩΔΙΩΣΗ', 'ΚΑΛΩΔΙΩΣΗ'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=30)),
                ('usage', models.CharField(choices=[('ΔΙΔΕΣ ΔΙΚΤΥΑΚΟΣ ΕΞΟΠΛΙΣΜΟΣ', 'ΔΙΔΕΣ ΔΙΚΤΥΑΚΟΣ ΕΞΟΠΛΙΣΜΟΣ'), ('ΣΔΑ ΠΥΡΣΕΙΑ', 'ΣΔΑ ΠΥΡΣΕΙΑ'), ('ΕΨΑΔ-ΤΗΛΕΦΩΝΙΚΟ ΚΕΝΤΡΟ', 'ΕΨΑΔ-ΤΗΛΕΦΩΝΙΚΟ ΚΕΝΤΡΟ'), ('ΚΡΥΠΤΟ', 'ΚΡΥΠΤΟ'), ('UPS', 'UPS'), ('ΛΟΙΠΑ ΥΛΙΚΑ', 'ΛΟΙΠΑ ΥΛΙΚΑ'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoHUDApp.product')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoHUDApp.recipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoHUDApp.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='DjangoHUDApp.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='DjangoHUDApp.warehouse')),
            ],
            options={
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
