# Generated by Django 5.0.1 on 2024-02-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='contact_person',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='notes',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
