# Generated by Django 5.0.1 on 2024-02-29 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0002_recipient_contact_person_recipient_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
