# Generated by Django 5.0.1 on 2024-03-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0004_remove_shipment_product_remove_shipment_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoHUDApp.warehouse'),
        ),
    ]
