# Generated by Django 5.0.1 on 2024-03-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0007_productinstance_delete_productserialnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
    ]
