# Generated by Django 5.0.1 on 2024-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0008_remove_product_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ΔΡΟΜΟΛΟΓΗΤΗΣ', 'ΔΡΟΜΟΛΟΓΗΤΗΣ'), ('CONVERTER', 'CONVERTER'), ('SWITCH', 'SWITCH'), ('MODULES', 'MODULE'), ('ΜΕΤΑΤΡΟΠΕΑΣ', 'ΜΕΤΑΤΡΟΠΕΑΣ'), ('LAN EXTENDER', 'LAN EXTENDER'), ('ΚΑΛΩΔΙΩΣΗ', 'ΚΑΛΩΔΙΩΣΗ'), ('ΛΟΙΠΑ ΥΛΙΚΑ', 'ΛΟΙΠΑ ΥΛΙΚΑ'), ('IP PHONES', 'IP PHONES'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.CharField(choices=[('ΔΙΔΕΣ ΔΙΚΤΥΑΚΟΣ ΕΞΟΠΛΙΣΜΟΣ', 'ΔΙΔΕΣ ΔΙΚΤΥΑΚΟΣ ΕΞΟΠΛΙΣΜΟΣ'), ('ΣΔΑ ΠΥΡΣΕΙΑ', 'ΣΔΑ ΠΥΡΣΕΙΑ'), ('ΕΨΑΔ-ΤΗΛΕΦΩΝΙΚΟ ΚΕΝΤΡΟ', 'ΕΨΑΔ-ΤΗΛΕΦΩΝΙΚΟ ΚΕΝΤΡΟ'), ('ΚΡΥΠΤΟ', 'ΚΡΥΠΤΟ'), ('UPS', 'UPS'), ('ΔΟΡΥΦΟΡΙΚΑ', 'ΔΟΡΥΦΟΡΙΚΑ'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=50),
        ),
    ]
