# Generated by Django 5.0.1 on 2024-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0009_alter_product_category_alter_product_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ΔΡΟΜΟΛΟΓΗΤΗΣ', 'ΔΡΟΜΟΛΟΓΗΤΗΣ'), ('CONVERTER', 'CONVERTER'), ('SWITCH', 'SWITCH'), ('MODULES', 'MODULES'), ('ΜΕΤΑΤΡΟΠΕΑΣ', 'ΜΕΤΑΤΡΟΠΕΑΣ'), ('LAN EXTENDER', 'LAN EXTENDER'), ('ΚΑΛΩΔΙΩΣΗ', 'ΚΑΛΩΔΙΩΣΗ'), ('ΛΟΙΠΑ ΥΛΙΚΑ', 'ΛΟΙΠΑ ΥΛΙΚΑ'), ('IP PHONES', 'IP PHONES'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=30),
        ),
    ]
