# Generated by Django 5.0.2 on 2024-03-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='unit',
            field=models.CharField(default='None Specified', max_length=100),
        ),
    ]
