# Generated by Django 5.0.2 on 2024-04-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0012_product_batch_number_product_unit_of_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='name',
            new_name='commanding_unit',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='unit',
            new_name='recipient_unit',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='location',
        ),
    ]
