# Generated by Django 5.0.2 on 2024-05-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0013_rename_name_recipient_commanding_unit_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='access_groups',
            field=models.ManyToManyField(related_name='access_warehouses', to='auth.group'),
        ),
    ]
