# Generated by Django 5.0.2 on 2024-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0014_remove_recipient_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='shipment_attachments/'),
        ),
    ]
