# Generated by Django 4.1.1 on 2024-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DjangoHUDApp', '0016_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='owners',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Product Owners'),
        ),
    ]
