# Generated by Django 5.0.6 on 2024-05-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0017_remove_product_owner_product_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, default='KAMIA EPILOGH', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='notes',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DjangoHUDApp.recipient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductInstance',
        ),
    ]
