# Generated by Django 5.0.6 on 2024-06-14 09:41

import DjangoHUDApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0020_alter_shipment_shipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[DjangoHUDApp.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='shipment_attachments/', validators=[DjangoHUDApp.models.validate_shipment_attachment]),
        ),
    ]
