# Generated by Django 5.0.6 on 2024-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0021_alter_product_image_alter_shipment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
