# Generated by Django 4.0.1 on 2024-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DjangoHUDApp', '0022_shipment_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='signatory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owners',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Product Owners'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='access_groups',
            field=models.ManyToManyField(related_name='access_warehouses', to='auth.Group'),
        ),
    ]
