# Generated by Django 4.0.1 on 2024-07-09 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0023_shipment_signatory_alter_product_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, default='KAMIA EPILOGH', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='commanding_unit',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipient_unit',
            field=models.CharField(db_index=True, default='None Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('IN', 'Εισερχόμενη'), ('OUT', 'Εξερχόμενη')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
